# Generated by Django 4.2.18 on 2025-01-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_wishlist_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_session',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user_session',
            field=models.CharField(default='', max_length=255),
        ),
    ]
