# Generated by Django 4.2.18 on 2025-01-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cart_user_remove_wishlist_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '11 Cart'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': '12 Wishlist'},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_attribute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.productattribute'),
        ),
    ]
